# Generated by Django 4.0.3 on 2022-10-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_venue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ('-name',)},
        ),
    ]
