# Generated by Django 4.0.3 on 2022-10-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_venue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ('name',)},
        ),
    ]
