# Generated by Django 4.0.3 on 2022-10-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_options_alter_venue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('event_date',)},
        ),
    ]
