# Generated by Django 4.0.3 on 2022-11-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={},
        ),
    ]
