# Generated by Django 4.0.3 on 2022-11-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_venue_book_alter_venue_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='book',
            field=models.BooleanField(blank=True, choices=[('1', 'Booking Now'), ('2', 'Already Booked')], default=1, max_length=10),
        ),
    ]
