# Generated by Django 4.0.3 on 2022-11-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_venue_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='images',
            field=models.ImageField(default=False, upload_to='venue/images', verbose_name='Upload Image'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='book',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
