# Generated by Django 4.0.3 on 2022-11-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_venue_images_alter_venue_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='images',
            field=models.ImageField(upload_to='venue/images', verbose_name='Upload Image'),
        ),
    ]
