# Generated by Django 4.0.3 on 2022-11-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
