# Generated by Django 4.0.3 on 2022-11-28 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Blog Title')),
                ('slug', models.SlugField(max_length=264, unique=True)),
                ('description', models.TextField(max_length=400, verbose_name='Description')),
                ('images', models.ImageField(upload_to='blog/postImages/', verbose_name='Upload Image')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Blog date')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('blog_author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
