# Generated by Django 4.0.3 on 2022-11-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blog_publish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
    ]
